# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main #pipeline will use this branch

pool:
  name: "Self-Hosted Kopi Machine"
  demands:
  - Agent.name -equals Kopi-SelfHosted-Machine
  

steps:
- script: echo 'suy thannnnnnnn'
